import { runtime } from '../../../core/runtime.js';
import { supportedProviders } from '../../../core/storage/registry.js';
import { ChannelHealthService } from '../../../core/health/channelHealthService.js';
import { assertExternalEndpoint } from '../../../core/security/endpointValidation.js';

export async function onRequestGet({ request, env }) { const app = runtime(env); const url = new URL(request.url); const channels = await app.repository.listChannels({ limit: url.searchParams.get('limit'), cursor: url.searchParams.get('cursor') }); return Response.json({ items: channels.map(publicChannel), nextCursor: channels.length ? channels.at(-1).cursor || null : null, allowedProviders: supportedProviders(), r2Disabled: true }); }
export async function onRequestPost({ request, env }) { let body; try { body = await request.json(); } catch { return Response.json({ error: 'Invalid JSON body' }, { status: 400 }); } if (body.provider === 'r2') return Response.json({ error: 'R2 is disabled in Zero-Cost mode' }, { status: 400 }); if (!supportedProviders().includes(body.provider)) return Response.json({ error: 'Unsupported provider' }, { status: 400 }); if (!body.name || !body.failureDomain) return Response.json({ error: 'name and failureDomain are required' }, { status: 400 }); if (hasSensitiveConfig(body.config) || !validSecretRefs(body.provider, body.secretRefs)) return Response.json({ error: 'Credentials must be supplied as valid secret references, not channel config' }, { status: 400 }); try { validateChannelConfig(body.provider, body.config || {}); const app = runtime(env); await app.guard.assertWrite({ admin: true }); const channel = await app.repository.createChannel({ id: body.id || `channel_${crypto.randomUUID()}`, name: body.name, provider: body.provider, failureDomain: body.failureDomain, priority: body.priority, config: body.config || {}, secretRefs: body.secretRefs || {}, capabilities: body.capabilities || {} }); await app.repository.audit({ id: `audit_${crypto.randomUUID()}`, action: 'channel.created', targetType: 'storage_channel', targetId: channel.id, details: { provider: channel.provider } }); return Response.json(publicChannel(channel), { status: 201 }); } catch (error) { return Response.json({ error: error.message || 'Invalid channel configuration', code: error.code || 'INVALID_CONFIGURATION' }, { status: error.code === 'ZERO_COST_GUARD' ? 503 : 400 }); } }
export async function onRequestPatch({ request, env }) { const body = await request.json(); const app = runtime(env); await app.guard.assertWrite({ admin: true }); if (!body.channelId) return Response.json({ error: 'channelId is required' }, { status: 400 }); let channel; if (body.action === 'enable' || body.action === 'disable') channel = await app.repository.setChannelEnabled(body.channelId, body.action === 'enable'); else if (body.action === 'health_check') channel = await new ChannelHealthService(app.repository, env).check(body.channelId); else return Response.json({ error: 'Unsupported action' }, { status: 400 }); if (!channel) return Response.json({ error: 'Channel not found' }, { status: 404 }); await app.repository.audit({ id: `audit_${crypto.randomUUID()}`, action: `channel.${body.action}`, targetType: 'storage_channel', targetId: channel.id }); return Response.json(publicChannel(channel)); }
function publicChannel(channel) { const { config_json, secret_refs_json, ...rest } = channel; return { ...rest, config: safeConfig(config_json), secretRefsConfigured: Object.keys(JSON.parse(secret_refs_json || '{}')) }; }
function safeConfig(value) { const config = JSON.parse(value || '{}'); for (const key of Object.keys(config)) if (/token|secret|password|authorization|username|headers/i.test(key)) delete config[key]; return config; }
export function hasSensitiveConfig(config) { return Object.entries(config || {}).some(([key, value]) => /token|secret|password|authorization|username/i.test(key) || (key === 'headers' && Object.keys(value || {}).some(header => /authorization|cookie/i.test(header)))); }
function validSecretRefs(provider, refs) { if (!refs || typeof refs !== 'object') return false; const values = Object.values(refs); if (!values.every(value => typeof value === 'string' && /^[A-Z][A-Z0-9_]{1,127}$/.test(value))) return false; if (provider === 'webdav') return Boolean(refs.usernameRef && refs.passwordRef); if (provider === 'telegram') return Boolean(refs.tokenRef); return true; }
function validateChannelConfig(provider, config) { if (provider === 'webdav') assertExternalEndpoint(config.baseUrl, { label: 'WebDAV baseUrl' }); if (provider === 'telegram' && config.proxyUrl) assertExternalEndpoint(config.proxyUrl, { label: 'Telegram proxyUrl' }); }
