import { runtime } from '../../../core/runtime.js';
import { supportedProviders } from '../../../core/storage/registry.js';
import { ChannelHealthService } from '../../../core/health/channelHealthService.js';

export async function onRequestGet({ request, env }) { const app = runtime(env); const url = new URL(request.url); const channels = await app.repository.listChannels({ limit: url.searchParams.get('limit'), cursor: url.searchParams.get('cursor') }); return Response.json({ items: channels.map(publicChannel), nextCursor: channels.length ? channels.at(-1).cursor || null : null, allowedProviders: supportedProviders(), r2Disabled: true }); }
export async function onRequestPost({ request, env }) { const body = await request.json(); if (body.provider === 'r2') return Response.json({ error: 'R2 is disabled in Zero-Cost mode' }, { status: 400 }); if (!supportedProviders().includes(body.provider)) return Response.json({ error: 'Unsupported provider' }, { status: 400 }); if (hasSensitiveConfig(body.config)) return Response.json({ error: 'Credentials must be supplied as secret references, not channel config' }, { status: 400 }); const app = runtime(env); await app.guard.assertWrite({ admin: true }); const channel = await app.repository.createChannel({ id: body.id || `channel_${crypto.randomUUID()}`, name: body.name, provider: body.provider, failureDomain: body.failureDomain || body.id || 'default', priority: body.priority, config: body.config || {}, secretRefs: body.secretRefs || {}, capabilities: body.capabilities || {} }); await app.repository.audit({ id: `audit_${crypto.randomUUID()}`, action: 'channel.created', targetType: 'storage_channel', targetId: channel.id, details: { provider: channel.provider } }); return Response.json(publicChannel(channel), { status: 201 }); }
export async function onRequestPatch({ request, env }) { const body = await request.json(); const app = runtime(env); await app.guard.assertWrite({ admin: true }); if (!body.channelId) return Response.json({ error: 'channelId is required' }, { status: 400 }); let channel; if (body.action === 'enable' || body.action === 'disable') channel = await app.repository.setChannelEnabled(body.channelId, body.action === 'enable'); else if (body.action === 'health_check') channel = await new ChannelHealthService(app.repository, env).check(body.channelId); else return Response.json({ error: 'Unsupported action' }, { status: 400 }); if (!channel) return Response.json({ error: 'Channel not found' }, { status: 404 }); await app.repository.audit({ id: `audit_${crypto.randomUUID()}`, action: `channel.${body.action}`, targetType: 'storage_channel', targetId: channel.id }); return Response.json(publicChannel(channel)); }
function publicChannel(channel) { const { config_json, secret_refs_json, ...rest } = channel; return { ...rest, config: safeConfig(config_json), secretRefsConfigured: Object.keys(JSON.parse(secret_refs_json || '{}')) }; }
function safeConfig(value) { const config = JSON.parse(value || '{}'); for (const key of Object.keys(config)) if (/token|secret|password|authorization/i.test(key)) delete config[key]; return config; }
export function hasSensitiveConfig(config) { return Object.keys(config || {}).some(key => /token|secret|password|authorization|username/i.test(key)); }
