import { runtime } from '../../../core/runtime.js';
import { FileService } from '../../../core/files/fileService.js';

export async function onRequestGet({ request, env }) { const app = runtime(env); const url = new URL(request.url); const id = url.searchParams.get('fileId'); if (id) { const file = await app.repository.getFile(id); if (!file) return Response.json({ error: 'File not found' }, { status: 404 }); return Response.json({ file: publicFile(file), replicas: (await app.repository.listReplicas(id)).map(publicReplica), tombstone: publicTombstone(await app.repository.getTombstone(id)), url: `/file/${id}` }); } const items = await app.repository.listFiles({ limit: url.searchParams.get('limit'), cursor: url.searchParams.get('cursor'), status: url.searchParams.get('status') }); return Response.json({ items: items.map(publicFile), nextCursor: items.length ? items.at(-1).cursor || null : null }); }
export async function onRequestDelete({ request, env }) { const app = runtime(env); const url = new URL(request.url); const id = url.searchParams.get('fileId'); if (!id) return Response.json({ error: 'fileId is required' }, { status: 400 }); try { const tombstone = await new FileService(app).delete(id, 'admin'); if (!tombstone) return Response.json({ error: 'File not found or deletion conflict' }, { status: 404 }); await app.repository.audit({ id: `audit_${crypto.randomUUID()}`, action: 'file.deleted', targetType: 'file', targetId: id }); return Response.json({ deleted: true, tombstone: publicTombstone(tombstone) }, { status: 202 }); } catch (error) { return guardedError(error); } }
export async function onRequestPost({ request, env }) { const body = await parseJson(request); if (!body) return Response.json({ error: 'Invalid JSON body' }, { status: 400 }); const { fileId, replicaId, action } = body; const app = runtime(env); if (!fileId || !replicaId || !['verify', 'repair', 'switch_primary'].includes(action)) return Response.json({ error: 'fileId, replicaId, and action are required' }, { status: 400 }); try { const file = await app.repository.getFile(fileId); const replica = await app.repository.getReplica(replicaId); if (!file || !replica || replica.file_id !== fileId) return Response.json({ error: 'File or replica not found' }, { status: 404 }); if (await app.repository.getTombstone(fileId)) return Response.json({ error: 'Deleted files cannot be modified' }, { status: 409 }); if (action === 'switch_primary') { await app.guard.assertWrite({ admin: true }); const primary = await app.repository.switchPrimaryReplica(fileId, replicaId); if (!primary) return Response.json({ error: 'Only a healthy synchronous replica can become primary' }, { status: 409 }); await app.repository.audit({ id: `audit_${crypto.randomUUID()}`, action: 'replica.primarySwitched', targetType: 'file_replica', targetId: replicaId }); return Response.json({ replica: publicReplica(primary) }); }
    if (action === 'verify') await app.guard.assertVerify(); else await app.guard.assertRepair({ critical: false }); if (await app.repository.getTombstone(fileId)) return Response.json({ error: 'Deleted files cannot be repaired' }, { status: 409 }); const operation = action === 'verify' ? 'VERIFY_REPLICA' : 'REPAIR_REPLICA'; const job = await app.jobs.create({ id: `job_${crypto.randomUUID()}`, fileId, replicaId, channelId: replica.channel_id, operation, generation: file.generation, idempotencyKey: `manual:${operation}:${fileId}:${replicaId}:${file.generation}` }); await app.repository.audit({ id: `audit_${crypto.randomUUID()}`, action: `replica.${action}Requested`, targetType: 'file_replica', targetId: replicaId }); return Response.json({ job: publicJob(job) }, { status: 202 }); } catch (error) { return guardedError(error); } }
function publicFile(file) { const { id, generation, status, name, content_type: contentType, size, is_public: isPublic, created_at: createdAt, updated_at: updatedAt, deleted_at: deletedAt, cursor } = file; return { id, generation, status, name, contentType, size, isPublic: Boolean(isPublic), createdAt, updatedAt, deletedAt, cursor }; }
function publicReplica(replica) { const { id, file_id: fileId, channel_id: channelId, provider, role, generation, status, size, etag, checksum, last_checked_at: lastCheckedAt, last_success_at: lastSuccessAt, last_error_code: lastErrorCode, last_error_message: lastErrorMessage, cursor } = replica; return { id, fileId, channelId, provider, role, generation, status, size, etag, checksum, lastCheckedAt, lastSuccessAt, lastErrorCode, lastErrorMessage, cursor }; }
function publicTombstone(tombstone) { if (!tombstone) return null; const { file_id: fileId, generation, reason, created_at: createdAt, finalized_at: finalizedAt } = tombstone; return { fileId, generation, reason, createdAt, finalizedAt }; }
function publicJob(job) { if (!job) return null; const { payload_json, ...safe } = job; return safe; }
async function parseJson(request) { try { return await request.json(); } catch { return null; } }
function guardedError(error) { return Response.json({ error: error.code === 'ZERO_COST_GUARD' ? 'Operation is paused by the Zero-Cost Guard' : 'Operation failed', code: error.code || 'OPERATION_FAILED', protectionLevel: error.level || null }, { status: error.code === 'ZERO_COST_GUARD' ? 503 : 400 }); }
